apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: okno-db
  name: database
spec:
  ports:
  - name: "port3306"
    protocol: TCP
    port: 3306
  type: ClusterIP
  selector:
    io.service: okno-db
