apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: okno-svc
  name: okno-svc
spec:
  ports:
  - name: "port7777"
    port: 7777
    protocol: TCP
  type: NodePort
  selector:
    io.service: okno-svc
status:
  loadBalancer: {}
