apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: okno-db
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: okno-db
  strategy: {}
  template:
    metadata:
      labels:
        io.service: okno-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: okno
        - name: MYSQL_PASSWORD
          value: haslo
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: user
        image: michalgawin/okno-db:0.1
        name: database
        args: ["--bind-address=0.0.0.0"]
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
