apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: okno-auth
  name: okno-auth
spec:
  ports:
  - name: "port6666"
    port: 6666
    protocol: TCP
  type: NodePort
  selector:
    io.service: okno-auth
status:
  loadBalancer: {}
